import "@/app/globals.css"
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
export const metadata = {
  title: "",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Nav/>
        <main>{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
